version: '3'

services:
  appgo:
    image: golang:1.19
    volumes:
      - ./appgo:/go/src/app
    ports:
      - "8000:8000"
  mysql:
    image:  mysql:5.7
    container_name: mysql_edilo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: checkin
      MYSQL_PASSWORD: root
    ports:
      - 3309:3309
    volumes:
    - ./mysql:/var/lib/mysql